public class ClientExample {
    private static Arsemi.ArsemiCore _asmCore = new();
    public const string PathToConfigFile = "path/to/config.json";

    public static async Task Main() {
        Console.WriteLine("Started Client!");
        Setup();
        bool exiting = false;
        while(!exiting) {
            exiting = await UpdateLoopAsync();
        }
    }

    /// <summary>
    /// Sets up each sensor, filters and other settings via code
    /// </summary>
    public static void Setup() {
        _asmCore.StartSetup();
        _asmCore.AddSensor(new Arsemi.Sensor.AnalogSensor(), "Heartrate")
            .AddFilter(new Arsemi.Sensor.Filter.BlaBlaFilter())
            .SetInterval(100)
            .AddEvent(Arsemi.Sensor.AbstractSensor.EventType.Threshold, "Excitement", 120);
        _asmCore.AddSensor(new Arsemi.Sensor.DigitalSensor(), "Button");
        _asmCore.SetInterval("Button", 200);
        _asmCore.FinishSetup();
        //ExampleConstants.Events.Excitement += EventAction;

        Arsemi.ArsemiConfig.SaveTo(_asmCore, PathToConfigFile, Arsemi.ArsemiConfig.ConfigType.JSON);
        _asmCore.StartLoop();
    }


    /// <summary>
    /// Example for reading sensor data continuously
    /// (C# constants can only be used if generated by calling -INSERT METHOD- or using the GUI beforehand)
    /// </summary>
    public static async Task<bool> UpdateLoopAsync() {
        //float currentGSR = (float)_asmCore.GetSensorValueID(2);
        float currentHeartrate = (float)_asmCore.GetSensorValue((uint)Arsemi.Examples.ExampleConstants.Sensors.Heartrate);
        Console.WriteLine(currentHeartrate);
        await Task.Delay(200).ConfigureAwait(false);
        return false;
    }

}