using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Arsemi.Sensor;
using Arsemi.Sensor.Event;
using Arsemi.Sensor.Filter;

namespace Arsemi {
    namespace Examples {
        /// <summary>
        /// Example for a C# class using the ArsemiCore
        /// </summary>
        public static class ConceptUsage {
            [JsonInclude] private static ArsemiCore _asmCore = new();
            public const string PathToConfigDirectory = "/home/mika/Downloads/ArsemiConfig/";


            public static async Task Main() {
                await Setup(); // Alternative: AutomaticSetup()
                bool exiting = false;
                while(!exiting) {
                    exiting = await UpdateLoopAsync();
                }
                await Exit();
            }


            /// <summary>
            /// Sets up each sensor, filters and other settings via code.
            /// Ideally this is done in the GUI and then only AutomaticSetup() called.
            /// </summary>
            public static async Task Setup() {
                _asmCore.StartSetup();
                AbstractSensor hr = _asmCore.AddSensor(new AnalogSensor(), "Heartrate");
                AbstractFilter butterworth = new ButterworthFilter(hr, 2);
                hr.AddFilter(butterworth, "Butterworth")
                    .SetInterval(100)
                    .AddEvent(new AboveThresholdEvent(15), "Excitement");
                _asmCore.AddSensor(new DigitalSensor(), "Button");
                _asmCore.SetInterval("Button", 200);
                _asmCore.FinishSetup();
                ArsemiConstants.Actions.Excitement += EventAction;

                await ConfigSaver.SaveTo(_asmCore, PathToConfigDirectory);
                await ConfigSaver.GenerateConstants(_asmCore, PathToConfigDirectory);
                _asmCore.StartLoop();
            }


            /// <summary>
            /// Setup everything once beforehand, the settings can be stored into a config file which can be reused in multiple projects
            /// without the need of an elaborate setup. So this is equal to Setup() but ONLY if the config-file from Setup() is saved.
            /// Also can be done in the GUI!
            /// </summary>
            public static async Task AutomaticSetup() {
                _asmCore.StartSetup();
                _asmCore = await ConfigSaver.LoadConfigAsync(PathToConfigDirectory);
                _asmCore.FinishSetup();
                _asmCore.StartLoop();
            }


            /// <summary>
            /// Example for reading sensor data continuously
            /// (C# constants can only be used if generated by calling -INSERT METHOD- or using the GUI beforehand)
            /// </summary>
            public static async Task<bool> UpdateLoopAsync() {
                //float currentGSR = (float)_asmCore.GetSensorValueID(2);
                float currentHeartrate = (float)_asmCore.GetSensorValue((uint)ArsemiConstants.Sensors.Heartrate);
                await Task.Delay(200).ConfigureAwait(false);
                return false;
            }


            /// <summary>
            /// When an event is emitted by the
            /// </summary>
            public static void EventAction() {
                Console.WriteLine("Event action function called!");
            }


            /// <summary>
            /// Execution of the microcontroller can be manually stopped (also stops upon exiting debugging)
            /// </summary>
            public static async Task Exit() {
                await _asmCore.StopLoop();
            }
        }
    }
}