using System.Threading.Tasks;

namespace Arsemi {
    namespace Examples {
        /// <summary>
        /// Example for a C# class using the ArsemiCore
        /// </summary>
        public static class ConceptUsage {
            private static ArsemiCore _asmCore = new();
            public const string PathToConfigFile = "path/to/config.json";


            public static async Task Main() {
                Setup(); // Alternative: AutomaticSetup()
                bool exiting = false;
                while(!exiting) {
                    exiting = await UpdateLoopAsync();
                }
                Exit();
            }


            /// <summary>
            /// Sets up each sensor, filters and other settings via code
            /// </summary>
            public static void Setup() {
                _asmCore.StartSetup();
                _asmCore.AddSensor(new Sensor.AnalogSensor(), "Heartrate")
                    .AddFilter(new Sensor.Filter.BlaBlaFilter())
                    .SetInterval(100)
                    .AddEvent(Sensor.AbstractSensor.EventType.Threshold, "Excitement", 120);
                _asmCore.AddSensor(new Sensor.DigitalSensor(), "Button");
                _asmCore.SetInterval("Button", 200);
                _asmCore.FinishSetup();
                ExampleConstants.Events.Excitement += EventAction;

                ArsemiConfig.SaveTo(_asmCore, PathToConfigFile, ArsemiConfig.ConfigType.JSON);
                //_asmCore.StartLoop();
            }


            /// <summary>
            /// Setup everything once beforehand, the settings can be stored into a config file which can be reused in multiple projects
            /// without the need of an elaborate setup. So this is equal to Setup() but ONLY if the config-file from Setup() is saved.
            /// Also can be done in the GUI!
            /// </summary>
            public static void AutomaticSetup() {
                _asmCore.StartSetup();
                _asmCore = ArsemiConfig.LoadConfiguration(PathToConfigFile);
                _asmCore.FinishSetup();
            }


            /// <summary>
            /// Example for reading sensor data continuously
            /// (C# constants can only be used if generated by calling -INSERT METHOD- or using the GUI beforehand)
            /// </summary>
            public static async Task<bool> UpdateLoopAsync() {
                //float currentGSR = (float)_asmCore.GetSensorValueID(2);
                float currentHeartrate = (float)_asmCore.GetSensorValue((uint)ExampleConstants.Sensors.Heartrate);
                Console.WriteLine(currentHeartrate);
                await Task.Delay(200).ConfigureAwait(false);
                return false;
            }


            /// <summary>
            /// When an event is emitted by the
            /// </summary>
            public static void EventAction() {
                // Insert code that gets executed when Arsemi emits an Action
            }


            /// <summary>
            /// Execution of the microcontroller can be manually stopped (also stops upon exiting debugging)
            /// </summary>
            public static void Exit() {
                _asmCore.StopLoop();
            }
        }
    }
}