using System.Text.Json.Serialization;
using Arsemi.IPC;
using Arsemi.Sensor;
using Arsemi.Sensor.Event;
using Arsemi.Sensor.Filter;
using Arsemi.Utilities;
using BenchmarkDotNet.Attributes;

namespace Arsemi {
    namespace Examples {
        /// <summary>
        /// Example for a C# class using the ArsemiCore
        /// </summary>
        public static class ConceptUsage {
            [JsonInclude] private static ArsemiCore _arsemiCore = new();
            public const string PathToConfigDirectory = "/home/mika/Downloads/ArsemiConfig/";
            public static Action? HeartrushAction;

            private static string _heartrushEventName = "Heartrush";


            public static async Task Main() {
                string stringPack = "1067:32:13";
                var size = sizeof(char) * stringPack.Length;
                byte[] binPack = [SerialProtocol.Action.System.Error, SerialProtocol.Error.Package.InvalidActionCode];
                size = sizeof(byte) * binPack.Length;
                byte[] safeBinPack = [SerialProtocol.PackageStartByte, SerialProtocol.Action.System.Error, SerialProtocol.Error.Package.InvalidActionCode, 20, SerialProtocol.PackageStartByte];
                size = sizeof(byte) * safeBinPack.Length;
                await Setup(); // Alternative: AutomaticSetup()
                bool exiting = false;
                while(!exiting) {
                    exiting = await UpdateLoopAsync();
                }
                await Exit();
            }


            /// <summary>
            /// Sets up each sensor, filters and other settings via code.
            /// Ideally this is done in the GUI and then only AutomaticSetup() called.
            /// </summary>
            [GlobalSetup]
            public static async Task Setup() {
                // _arsemiCore.DebugClass();
                // return;

                // AbstractSensor hr = _arsemiCore.AddSensor(new MAX30102Sensor("Heartrate"));
                // AbstractFilter butterworth = new ButterworthFilter(hr, 2);
                // hr.AddFilter(butterworth, "Butterworth")
                //     .SetInterval(100);
                // .AddEvent(new AboveThresholdEvent(15), "Excitement");

                _arsemiCore.AddSensor(new DigitalSensor("Button", 2))
                        .SetInterval(100)
                        .AddEvent(_heartrushEventName, rb => EventCondition.AboveThreshold(rb, 50))
                        .AddFilter(FilterAliases.ButterworthHighPassFilter(100, 10), "Highpass");
                if(await _arsemiCore.ConnectMicrocontrollerAsync() != MessageParsing.ConnectionResult.SUCCESS)
                    return;
                _arsemiCore.FinishSetup();

                //await ConfigSaver.SaveTo(_arsemiCore, PathToConfigDirectory);
                //await ConfigSaver.GenerateGlobals(_arsemiCore, PathToConfigDirectory);
                // ArsemiGlobals.Events.Excitement += EventAction;
                _arsemiCore.StartLoop();
                _arsemiCore.EventReceived += HandleEvent;
            }


            /// <summary>
            /// Setup everything once beforehand, the settings can be stored into a config file which can be reused in multiple projects
            /// without the need of an elaborate setup. So this is equal to Setup() but ONLY if the config-file from Setup() is saved.
            /// Also can be done in the GUI!
            /// </summary>
            public static async Task AutomaticSetup() {
                _arsemiCore = await ConfigSaver.LoadConfigAsync(PathToConfigDirectory);
                _arsemiCore.FinishSetup();
                _arsemiCore.StartLoop();
            }


            /// <summary>
            /// Example for reading sensor data continuously
            /// (C# constants can only be used if generated by calling -INSERT METHOD- or using the GUI beforehand)
            /// </summary>
            public static async Task<bool> UpdateLoopAsync() {
                // float currentButton = (float)_arsemiCore.GetSensorValue((uint)ArsemiGlobals.Sensors.GSR);
                // float currentHeartrate = (float)_arsemiCore.GetSensorValue((uint)ArsemiGlobals.Sensors.Heartrate);
                await Task.Delay(200).ConfigureAwait(false);
                return false;
            }


            /// <summary>
            /// When an event is emitted
            /// </summary>
            public static void HandleEvent(EventData eventData) {
                Console.WriteLine("Event: " + eventData.Name + " has been invoked by sensor: " + eventData.Sensor?.Data.Name + ".");
            }


            /// <summary>
            /// Execution of the microcontroller can be manually stopped (also stops upon exiting debugging)
            /// </summary>
            public static async Task Exit() {
                await _arsemiCore.StopLoop();
            }
        }
    }
}